# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 22:19
from __future__ import unicode_literals

from django.db import migrations

import csv


def rater_data(apps, schema_editor):
    Rater = apps.get_model("movieratings_app", "Rater")

    with open("/Users/Tootie/TIY-projects/movieratings/movieratings_app/ml-100k/u.user") as outfile:
        rater = csv.DictReader(outfile, fieldnames=["rater_id", "age", "gender", "occupation", "zipcode"],
                               delimiter="|")
        for row in rater:
            Rater.objects.create(rater_id=int(row['rater_id']), age=int(row['age']),
                                 gender=row['gender'], occupation=row['occupation'], zipcode=row['zipcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rater_data)
    ]
