# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 15:31
from __future__ import unicode_literals

from django.db import migrations

import csv


def movie_data(apps, schema_editor):
    Movie = apps.get_model("movieratings_app", "Movie")
    with open("/Users/Tootie/TIY-projects/movieratings/movieratings_app/u.item", encoding="latin1") as outfile:
        movie = csv.DictReader(outfile, fieldnames=["item_id", "title", "release_date", "video_release",
                                                    "imdb_url", "unknown", "action", "adventure", "animation",
                                                    "children", "comedy", "crime", "documentary", "drama", "fantasy",
                                                    "film_noir", "horror", "musical", "mystery", "romance", "sci_fi",
                                                    "thriller", "war", "western"], delimiter="|")
        for row in movie:
            Movie.objects.create(id=int(row['item_id']), title=row["title"],
                                 release_date=row["release_date"], video_release=row["video_release"],
                                 imdb_url=row["imdb_url"], unknown=int(row["unknown"]), action=int(row["action"]),
                                 adventure=int(row["adventure"]), animation=int(row["animation"]),
                                 children=int(row["children"]), comedy=int(row["comedy"]), crime=int(row["crime"]),
                                 documentary=int(row["documentary"]), drama=int(row["drama"]),
                                 fantasy=int(row["fantasy"]), film_noir=int(row["film_noir"]),
                                 horror=int(row["horror"]), musical=int(row["musical"]), mystery=int(row["mystery"]),
                                 romance=int(row["romance"]), sci_fi=int(row["sci_fi"]), thriller=int(row["thriller"]),
                                 war=int(row["war"]), western=int(row["western"]))




class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0002_auto_20160609_2219'),
    ]

    operations = [
        migrations.RunPython(movie_data)
    ]
