# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:03
from __future__ import unicode_literals

from django.db import migrations

import csv


def rating_data(apps, schema_editor):
    Rater = apps.get_model("movieratings_app", "Rater")
    Movie = apps.get_model("movieratings_app", "Movie")
    Rating = apps.get_model("movieratings_app", "Rating")

    with open("/Users/Tootie/TIY-projects/movieratings/movieratings_app/u.data") as outfile:
        rating = csv.DictReader(outfile, fieldnames=["rater_id", "item_id",
                                "rating", "timestamp"], delimiter="\t")

        for row in rating:
            print(row)
            temp_rater_id = Rater.objects.get(rater_id=int(row['rater_id']))
            temp_item_id = Movie.objects.get(item_id=int(row['item_id']))

            Rating.objects.create(id=temp_rater_id, item_id=temp_item_id,
                                   rating=int(row['rating']), timestamp=int(row['timestamp']))


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0003_auto_20160610_1531'),
    ]

    operations = [
        migrations.RunPython(rating_data)
    ]
