# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0004_auto_20160610_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater_id',
            new_name='rater',
        ),
    ]
